services:
  - type: web
    name: mclc-order-management
    env: python
    buildCommand: pip install -r Backend/requirements.txt uvicorn fastapi sqlalchemy pydantic python-dotenv
    startCommand: uvicorn Backend.main:app --host 0.0.0.0 --port $PORT
